spring:
  application:
    name: RoomCleaningSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
  profiles:
    active: ${ENV:prod}